### ISSUE TITLE
[REQ] UV/vertex level map painting ?

### ISSUE THREAD

**Issue by NicTanghe** [PrismPipeline/QuiltiX#19]
Hello I haven't seen if it exists yet, but I immediately get the idea that if someone could take the time and effort to get UV map painting in to QuilitiX it would increase Its value tenfold. Vertex level painting would also be a great addition.

Although, python on its own probably won’t be fast enough. And you could probably just use Houdini.

**Comment by RichardFrangenberg** [comment]
That would be great to have, but it's a bit out of the current scope. For now the focus is to support more Mtlx/Usd specific features.
