### ISSUE TITLE
Incorrect handling of normals in default viewport?

### ISSUE THREAD

**Issue by ajenyon** [PrismPipeline/QuiltiX#20]
Method:

Download prebuilt windows binary (v0.4.0) 
Load default scene, and the included 'Motley_patchwork_rug' material
Choose file > Open in MaterialXView

Compare the results

![Render_error_comparison](https://github.com/PrismPipeline/QuiltiX/assets/33992322/5e7ac77b-40a8-43ac-a081-dcdec3988763)

The IBL setup is not identical, so we wouldn't expect a 100% perfect match - but the normals look like they are sampling the backfacing surface.

The issue is even clearer when looking towards a bright area of the HDRI:

![Render_error](https://github.com/PrismPipeline/QuiltiX/assets/33992322/2517c0db-c0a0-402e-ade5-55a965bf48b3)

Removing the normal, coat normal and tangent connections in the material 'fixes' the issue, though obviously not in a useful way.

**Comment by RichardFrangenberg** [comment]
This is a problem in USD (Storm Hydra delegate): https://github.com/PixarAnimationStudios/OpenUSD/issues/1585
So unfortunately it's not something we can fix in QuiltiX.
To view the correct normals you can change the renderer in QuiltiX to Arnold or any other available delegates.

**Comment by ajenyon** [comment]
Copy!  Thanks for the reply.
