### ISSUE TITLE
Relative paths are not valid in Quiltix editor

### ISSUE THREAD

**Issue by ajenyon** [PrismPipeline/QuiltiX#22]
Description of issue:

I want to load my textures as relative rather than absolute paths (as the demo materials), so the MaterialX material is able to be copied to different locations on disk (or another disk entirely), and still load correctly.  This doesn't appear to work with the current BETA.

Method:

Download prebuilt windows binary (v0.4.0)
Load default scene, and the included 'Motley_patchwork_rug' material
Change the file path of the Diffuse texture to match the relative path encoded in the materialX file

![Paths_materialX_file](https://github.com/PrismPipeline/QuiltiX/assets/33992322/ef86c6f7-5e0a-4bea-b495-cb8bfe001b08)

![Paths_Quiltix_editor](https://github.com/PrismPipeline/QuiltiX/assets/33992322/bf35f1fb-778b-44a6-a317-850da8d1ca07)

Expected result:
The texture loads as before

Actual result:
The texture fails to load, and the material goes black

![Paths_Quiltix_black](https://github.com/PrismPipeline/QuiltiX/assets/33992322/465d5161-8b8b-4a75-a2f5-2df96dfacb1d)

Edit:  Saving this path edit as a .mtlx and reloading it IS valid - the relative paths are converted back to absolute paths, and the textures display in the viewport as before.

**Comment by manuelkoester** [comment]
Hey!  
Thanks for the detailed description.

I remember this being an active temporary decision sometime during the development to enable QuiltiX's pipeline. But good that it has popped up again :)

We were thinking of adding a context menu option to convert between relative and absolute paths. This is a bit more involved however.  
Also we need to investigate if UsdMtlx can currently handle relative paths as it doesn't really know about the .mtlx document path at that point. We might be able to add to feed a `converted` document to UsdMtlx which only contains absolute paths.

**Comment by RichardFrangenberg** [comment]
this has been fixed now: https://github.com/PrismPipeline/QuiltiX/pull/23
