### ISSUE TITLE
Multiple issues video

### ISSUE THREAD

**Issue by zicher3d** [PrismPipeline/QuiltiX#24]
I'm not sure if all the issues I see are due to my machine missing something. I'm posting a video showing a few of them and seek advice.

https://github.com/PrismPipeline/QuiltiX/assets/7254958/3d82e0db-cd9c-4af4-8d7d-ca00cde73367

**Comment by melMass** [comment]
I can confirm this, this get's logged in the console when dropping the wire on the input:

```sh
DEBUG:QuiltiX.qx_nodegraph:updated mx xml data
Traceback (most recent call last):
  File "QuiltiX_win_v0.4.0/python_libs\NodeGraphQt\base\graph.py", line 410, in _on_connection_changed
    node1 = self._model.nodes[p1_view.node.id]
AttributeError: 'NoneType' object has no attribute 'id'
DEBUG:QuiltiX.qx_nodegraph:updated mx xml data
Traceback (most recent call last):
  File "QuiltiX_win_v0.4.0/python_libs\NodeGraphQt\base\graph.py", line 410, in _on_connection_changed
    node1 = self._model.nodes[p1_view.node.id]
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by manuelkoester** [comment]
Hey zicher and mel for catching these. I will break the video down into individual issues the coming days.

**Comment by manuelkoester** [comment]
Hey!
I just split up the mentioned problems from the video into seperate issues so we can tackle them one by one. Thank you very much for your feedback and submitting these 🙏

**Comment by manuelkoester** [comment]
All of the mentioned issues here are now resolved thanks to @RichardFrangenberg 🥳 
Thanks for raising them
