### ISSUE TITLE
PyPi page documentation

### ISSUE THREAD

**Issue by kwokcb** [PrismPipeline/QuiltiX#26]
Leaving a note that the PyPi has some minor documentation issues:

1. There  is a a few missing images.
2. The table of contents are using markdown links (which don't work in html :) , as well as the LICENSE link )

**Comment by manuelkoester** [comment]
Hey Bernard,

Thanks for the catch on the images. We are trying to support both dark and light mode on Github so we have two versions of the QuiltiX image in the Readme. I guess I will fix the light mode image for pypi, so it works there but keep the broken dark mode one, so only the light mode one will show on pypi and the dark mode one will be hidden (broken).

The Table of content will also be fixed.

**Comment by manuelkoester** [comment]
Regarding the table of contents I found the upstream issue which would eventually trickle up to this repo:

https://github.com/github/cmark-gfm/issues/186


There is a workaround for this which is manually adding the html anchors into the markdown file, but seems like some markdown renderers struggle with this..

I found that even large packages like [pandas](https://pypi.org/project/pandas/) or [pytorch](https://pypi.org/project/torch/) have the same issue.
