### ISSUE TITLE
Switch to official MaterialX PyPi distributed package

### ISSUE THREAD

**Issue by manuelkoester** [PrismPipeline/QuiltiX#33]
Since release https://github.com/AcademySoftwareFoundation/MaterialX/releases/tag/v1.38.8 it is possible to install MaterialX via PyPi. We can therefore remove the dependency to our patchy version :)
USD still remains though :(

**Comment by heavyrain266** [comment]
Official OpenUSD package on PyPi wouldn't make any sense. It has too many feature gates as compile-time flags. Until recently MaterialX also was optional, I believe that Python API still is disabled in default build config.

In other words, OpenUSD is designed for redistribution with feature sets that are required by each DCC, ex. builds from Autodesk won't work that well in Houdini.

**Comment by kwokcb** [comment]
Sorry for butting in, but I am curious here. 

I'm running a local build of `QuiltiX` (synced to head) and a local install of MaterialX (1.38.9). It seems to work as that's the version that shows up in the "Loaded Versions" dialog. 

I know that this be out of sync with released OpenUSD distributions (as 1.38.9 is not even out yet) but:
1. Will the search for `libraries` find the installed version (I think it does as it's using `mx.getDefaultSearchPath()`). 
2. Are there any caveats with just trying to build graphs.
3. If I have a custom build of UsdView (say synced to 1.38.9) will this work.

I'm mostly interested in graph creation at this point. 
Thanks.

**Comment by RichardFrangenberg** [comment]
Hey @kwokcb 

I think in your case only the MaterialX Python module is v1.38.9, but the stdlib definitions are loaded from an older mtlx version.

1. There are a few places where QuiltiX searches for the stdlib. You can find that here::
https://github.com/PrismPipeline/QuiltiX/blob/d6466f954553c622aed1ef58c66911486c361e95/src/QuiltiX/mx_node.py#L25

As you can see there are a few things, which get checked before the `mx.getDefaultDataSearchPath()`.
If you are using the USD build, which we provided, then QuiltiX will probably load these stdlib definitions:
https://github.com/PrismPipeline/OpenUSD_build/tree/22.08-win/pxr/libraries

To confirm that you can check the returned stdlib path in this function:
https://github.com/PrismPipeline/QuiltiX/blob/d6466f954553c622aed1ef58c66911486c361e95/src/QuiltiX/quiltix.py#L671C16-L671C16

2. Once you have the correct stdlibs loaded everything should work fine.

3. I'm currently testing it with USD 23.11 and Mtlx 1.38.8. I still need to test it more, but so far no problems. So I guess Mtlx 1.38.9 would work too, but you're probably the first one to test this.

**Comment by manuelkoester** [comment]
Will close this issue as we are now relying on the materialx package with the latest QuiltiX release. 
But please feel free to continue the conversation @kwokcb .
Manuel
