### ISSUE TITLE
Query: What is the JSON save file used for ?

### ISSUE THREAD

**Issue by kwokcb** [PrismPipeline/QuiltiX#35]
## Query

Not an issue but wondering what is the JSON file which you save using `RMB->Save As` in the graph used for ?
Can you load it back in for instance ?

Not a high priority. Just curious. Thanks.

**Comment by RichardFrangenberg** [comment]
This is a feature of the [NodegraphQt](https://github.com/jchanvfx/NodeGraphQt) project, which is meant for saving and loading nodegraphs.
However in QuiltiX I prefer to save everything in .mtlx files including the node position and meta data.
Probably we should remove the option to save json files to avoid any confusion.

**Comment by kwokcb** [comment]
Thanks. 

I was guessing this was a Qt thing :).  Maybe be good to hide this as it could be confusing. Or change it
to just do the same as "Save Materialx" from the main file menu.
