### ISSUE TITLE
Provide compiled arnold-usd download

### ISSUE THREAD

**Issue by manuelkoester** [PrismPipeline/QuiltiX#36]
Currently we are not yet providing a python venv friendly arnold download yet.

Additionally arnold-usd does not seem to behave nicely with USD + MaterialX starting with USD 23.08 (have not tested everything).
See upstream issue https://github.com/Autodesk/arnold-usd/issues/1751

**Comment by RichardFrangenberg** [comment]
Here are the Arnold precompiled binaries:
https://github.com/PrismPipeline/arnold-usd/releases/tag/v7.2.5.2

**Comment by manuelkoester** [comment]
Nice! Could you potentially also document how to use them in the `README`? <3

**Comment by RichardFrangenberg** [comment]
Of course: https://github.com/PrismPipeline/arnold-usd/blob/master/README.md

**Comment by manuelkoester** [comment]
Perfect, I'll add the same section to the QuiltiX readme later
