### ISSUE TITLE
Inputs with "channel" qualifiers loads with errors

### ISSUE THREAD

**Issue by kwokcb** [PrismPipeline/QuiltiX#40]
## Issue

Type matching does not take into consideration "channels" qualifiers. That is an input can have a channels qualifier which extracts out a set of channels from an upstream output. For example if "r" is specified on an upstream "color3" type then the type is essentially a "float" and can be connected to a downstream input.

# Example

If you load in the [glTF "boom box example"] https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/resources/Materials/Examples/GltfPbr/gltf_pbr_boombox.mtlx

This is the result (the upstream `multioutput` connection missing is an existing logged issue #34).

![image](https://github.com/PrismPipeline/QuiltiX/assets/49369885/6489549a-54d4-43c6-a75c-113064f03eba)

The following errors occur.

![image](https://github.com/PrismPipeline/QuiltiX/assets/49369885/9ea41776-ff33-4f2e-ac68-fe64be28d9c7)

(The node input binding errors can be ignored since it just does not find the file textures).

In this case the glTF pbr shader is extracting out red, green and blue channels from an upstream color3 image node and routing this to an 3 inputs each of "float" type.

**Note that is is a very common workflow of encoding multiple channels into a single image for glTF PBR nodes (occlusion, roughness, metallic).**

**Comment by kwokcb** [comment]
As a added note, I found that the "channels" attribute is lost on load, thus causing a MTLX validation error.

Note that [OpenPBR](https://github.com/AcademySoftwareFoundation/OpenPBR/tree/main) is currently using "channels" so that new shading model does not load in properly. (I have left a ping with OpenPBR folks to change to not use this but TBD what happens here)

**Comment by RichardFrangenberg** [comment]
It looks like the "channels" attribute disappeared from OpenPBR in the latest version.
I can see the "channels" attribute in the 1.38 specification, but it looks like in 1.39 it was removed.
I would expect to find it in this section:
https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/Specification/MaterialX.Specification.md#inputs

Can you confirm that the "channels" attribute is deprecated? @kwokcb 
If so, I wouldn't start adding support for it in QuiltiX anymore.

**Comment by kwokcb** [comment]
Hi @RichardFrangenberg ,
Yes, `channels` has been removed for 1.39 so no need to add support :). 

The upgrade process will replace these with additional nodes on file load by default. 

If there are problems then please log an issue. I did not run into issues with `OpenPBR` at least with the HDStorm delegate and don't see any `channels` usage. That said, please check that you have the latest revision where I have put in some fixes to the upgrade path. Thanks.

**Comment by RichardFrangenberg** [comment]
great! Then I'll close this. If I'll notice any problems with OpenPBR I'll open a new issue.
