### ISSUE TITLE
PySide2 distribution not found on Mac 

### ISSUE THREAD

**Issue by kwokcb** [PrismPipeline/QuiltiX#43]
## Issue

I'm trying to install on a Mac M2 running  Ventura 13.2.1. (Either directly from PyPi or a local build). This is with Python 3.10.9 installed.

Wheever I try to install I get this error:

```shell
INFO: pip is looking at multiple versions of quiltix to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement PySide2>=5.12 (from quiltix) (from versions: none)
ERROR: No matching distribution found for PySide2>=5.12
```

I tried installing PySide2 explicit with no luck as well. 
```shell
ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2
```

I assume I have something set up incorrectly ? 
Thanks for any help to resolve this.

**Comment by eric-with-a-c** [comment]
@kwokcb I think this is because there isn't a PyPi package of PySide2 for Apple Silicon.  What I did was switch my shell to use x86 via Rosetta2 with `arch -x86_64 /bin/zsh` and then with a  universal build of Python (i.e. not the Python that's installed using miniconda) pip installed QuiltiX. Once the environment was all x86 everything installed and ran as expected.

**Comment by CreateTheImaginable** [comment]
@kwokcb / @eric-with-a-c the real fix for this would be to upgrade QuiltiX from PySide2 to PySide6!    Does anyone know if that is in the roadmap? 🙏

**Comment by hybridherbst** [comment]
Running into the same issue here. The workaround of switching architecture as described above works for now :)

**Comment by manuelkoester** [comment]
Hey!

This is definitely something on our mind for 2024 as we want to stay on the VFX reference platform: https://vfxplatform.com/  

As a lot of other projects will have to do this transition next year I would love to hook onto their solutions to this problem. One way forward could be to transition to [qtpy](https://github.com/spyder-ide/qtpy) like other recent projects in this space are using: https://github.com/BigRoy/usd-qtpy/blob/main/pyproject.toml#L26C6-L26C10

**Comment by hybridherbst** [comment]
I believe USD can use either [PySide2 or PySide6 for usdview](https://github.com/PixarAnimationStudios/OpenUSD?tab=readme-ov-file#getting-and-building-the-code)

**Comment by manuelkoester** [comment]
Oh interesting. Seems like [usdview created its own sim around these versions](https://github.com/PixarAnimationStudios/OpenUSD/blob/release/pxr/usdImaging/usdviewq/qt.py).  
Currently we are a bit constrainted to what [NodeGraphQt](https://github.com/jchanvfx/NodeGraphQt) will be doing as we rely on it very heavily for basically all of our UI.

**Comment by manuelkoester** [comment]
But there are several open issues on it and [even an open PR](https://github.com/jchanvfx/NodeGraphQt/pull/327), so I don't worry too much that this will be a tough issue to solve. But it will still be quite time extensive and I would not want to move forward before NodeGraphQt has not upgraded.
